[errorprone] Fix BoxedPrimitiveEquality in BlockedThreadsConfigurator
Errorprone raises this error during the bazel build:

BlockedThreadsConfigurator.java:101: error: [BoxedPrimitiveEquality]
Comparison using reference equality instead of value equality.
Reference equality of boxed primitive types is usually not useful,
as they are value objects, and it is bug-prone, as instances are cached
for some values but not others.
      return Boolean.TRUE == entry.getKey()
                          ^
    (see https://errorprone.info/bugpattern/BoxedPrimitiveEquality)
  Did you mean 'return Objects.equals(Boolean.TRUE, entry.getKey())'
  or 'return Boolean.TRUE.equals(entry.getKey())'?

Change-Id: Icf1c32bfad64589d8bcc2d164342c1f2f436d447